/*
    DiscordJS allow for up to 25 choices in a SlashCommand's option

    This array stores which styles will be shown to the user, pick your favorites
*/
const styleOptions =
[
    { "name": "Random" },
    { "name": "Artstyle Abstract" },
    { "name": "Artstyle Hyperrealism" },
    { "name": "Cel Shaded Art" },
    { "name": "Dark Fantasy" },
    { "name": "Doodle Art" },
    { "name": "Flat 2d Art" },
    { "name": "Fortnite Art Style" },
    { "name": "Futuristic Cyberpunk Cityscape" },
    { "name": "Game Retro Game" },
    { "name": "Logo Design" },
    { "name": "Mk Alcohol Ink Art" },
    { "name": "Mk Ukiyo E" },
    { "name": "Mk Van Gogh" },
    { "name": "Misc Gothic" },
    { "name": "Misc Lovecraftian" },
    { "name": "MRE Anime" },
    { "name": "MRE Surreal Painting" },
    { "name": "Pencil Sketch Drawing" },
    { "name": "SAI Anime" },
    { "name": "SAI Comic Book" },
    { "name": "SAI Pixel Art" },
    { "name": "Simple Vector Art" },
    { "name": "Sticker Designs" },
    { "name": "Watercolor 2" }
]

module.exports = styleOptions;

/*
    All available styles for reference

const spans = document.querySelectorAll("#component-231 > [data-testid='checkbox-group'] > label > span");
const texts = Array.from(spans).map(span => span.textContent);
console.log(texts.sort());
*/

const allStyles =
[
    [
        "Abstract Expressionism",
        "Academia",
        "Action Figure",
        "Adorable 3D Character",
        "Adorable Kawaii",
        "Ads Advertising",
        "Ads Automotive",
        "Ads Corporate",
        "Ads Fashion Editorial",
        "Ads Food Photography",
        "Ads Gourmet Food Photography",
        "Ads Luxury",
        "Ads Real Estate",
        "Ads Retail",
        "Art Deco",
        "Art Nouveau",
        "Artstyle Abstract",
        "Artstyle Abstract Expressionism",
        "Artstyle Art Deco",
        "Artstyle Art Nouveau",
        "Artstyle Constructivist",
        "Artstyle Cubist",
        "Artstyle Expressionist",
        "Artstyle Graffiti",
        "Artstyle Hyperrealism",
        "Artstyle Impressionist",
        "Artstyle Pointillism",
        "Artstyle Pop Art",
        "Artstyle Psychedelic",
        "Artstyle Renaissance",
        "Artstyle Steampunk",
        "Artstyle Surrealist",
        "Artstyle Typography",
        "Artstyle Watercolor",
        "Astral Aura",
        "Avant Garde",
        "Baroque",
        "Bauhaus Style Poster",
        "Blueprint Schematic Drawing",
        "Caricature",
        "Cel Shaded Art",
        "Character Design Sheet",
        "Cinematic Diva",
        "Classicism Art",
        "Color Field Painting",
        "Colored Pencil Art",
        "Conceptual Art",
        "Constructivism",
        "Cubism",
        "Dadaism",
        "Dark Fantasy",
        "Dark Moody Atmosphere",
        "Dmt Art Style",
        "Doodle Art",
        "Double Exposure",
        "Dripping Paint Splatter Art",
        "Expressionism",
        "Faded Polaroid Photo",
        "Fauvism",
        "Flat 2d Art",
        "Fooocus Cinematic",
        "Fooocus Enhance",
        "Fooocus Masterpiece",
        "Fooocus Negative",
        "Fooocus Photograph",
        "Fooocus Pony",
        "Fooocus Semi Realistic",
        "Fooocus Sharp",
        "Fooocus V2",
        "Fortnite Art Style",
        "Futurism",
        "Futuristic Biomechanical",
        "Futuristic Biomechanical Cyberpunk",
        "Futuristic Cybernetic",
        "Futuristic Cybernetic Robot",
        "Futuristic Cyberpunk Cityscape",
        "Futuristic Futuristic",
        "Futuristic Retro Cyberpunk",
        "Futuristic Retro Futurism",
        "Futuristic Sci Fi",
        "Futuristic Vaporwave",
        "Game Bubble Bobble",
        "Game Cyberpunk Game",
        "Game Fighting Game",
        "Game Gta",
        "Game Mario",
        "Game Minecraft",
        "Game Pokemon",
        "Game Retro Arcade",
        "Game Retro Game",
        "Game Rpg Fantasy Game",
        "Game Strategy Game",
        "Game Streetfighter",
        "Game Zelda",
        "Glitchcore",
        "Glo Fi",
        "Googie Art Style",
        "Graffiti Art",
        "Harlem Renaissance Art",
        "High Fashion",
        "Idyllic",
        "Impressionism",
        "Infographic Drawing",
        "Ink Dripping Drawing",
        "Japanese Ink Drawing",
        "Knolling Photography",
        "Light Cheery Atmosphere",
        "Logo Design",
        "Luxurious Elegance",
        "MRE Ancient Illustration",
        "MRE Anime",
        "MRE Artistic Vision",
        "MRE Bad Dream",
        "MRE Brave Art",
        "MRE Cinematic Dynamic",
        "MRE Comic",
        "MRE Dark Cyberpunk",
        "MRE Dark Dream",
        "MRE Dynamic Illustration",
        "MRE Elemental Art",
        "MRE Gloomy Art",
        "MRE Heroic Fantasy",
        "MRE Lyrical Geometry",
        "MRE Manga",
        "MRE Space Art",
        "MRE Spontaneous Picture",
        "MRE Sumi E Detailed",
        "MRE Sumi E Symbolic",
        "MRE Surreal Painting",
        "MRE Undead Art",
        "MRE Underground",
        "Macro Photography",
        "Mandola Art",
        "Marker Drawing",
        "Medievalism",
        "Minimalism",
        "Misc Architectural",
        "Misc Disco",
        "Misc Dreamscape",
        "Misc Dystopian",
        "Misc Fairy Tale",
        "Misc Gothic",
        "Misc Grunge",
        "Misc Horror",
        "Misc Kawaii",
        "Misc Lovecraftian",
        "Misc Macabre",
        "Misc Manga",
        "Misc Metropolis",
        "Misc Minimalist",
        "Misc Monochrome",
        "Misc Nautical",
        "Misc Space",
        "Misc Stained Glass",
        "Misc Techwear Fashion",
        "Misc Tribal",
        "Misc Zentangle",
        "Mk Adnate Style",
        "Mk Afrofuturism",
        "Mk Albumen Print",
        "Mk Alcohol Ink Art",
        "Mk Andy Warhol",
        "Mk Anthotype Print",
        "Mk Aquatint Print",
        "Mk Atompunk",
        "Mk Basquiat",
        "Mk Bauhaus Style",
        "Mk Blacklight Paint",
        "Mk Bromoil Print",
        "Mk Calotype Print",
        "Mk Carnival Glass",
        "Mk Chicano Art",
        "Mk Chromolithography",
        "Mk Cibulak Porcelain",
        "Mk Color Sketchnote",
        "Mk Coloring Book",
        "Mk Constructivism",
        "Mk Cross Processing Print",
        "Mk Cross Stitching",
        "Mk Cyanotype Print",
        "Mk Dayak Art",
        "Mk De Stijl",
        "Mk Dufaycolor Photograph",
        "Mk Embroidery",
        "Mk Encaustic Paint",
        "Mk Fayum Portrait",
        "Mk Gond Painting",
        "Mk Gyotaku",
        "Mk Halftone Print",
        "Mk Herbarium",
        "Mk Illuminated Manuscript",
        "Mk Inuit Carving",
        "Mk Kalighat Painting",
        "Mk Lite Brite Art",
        "Mk Luminogram",
        "Mk Madhubani Painting",
        "Mk Mokume Gane",
        "Mk Mosaic",
        "Mk One Line Art",
        "Mk Palekh",
        "Mk Patachitra Painting",
        "Mk Pichwai Painting",
        "Mk Pictorialism",
        "Mk Pollock",
        "Mk Punk Collage",
        "Mk Ron English Style",
        "Mk Samoan Art Inspired",
        "Mk Scrimshaw",
        "Mk Shepard Fairey Style",
        "Mk Shibori",
        "Mk Singer Sargent",
        "Mk Suminagashi",
        "Mk Tlingit Art",
        "Mk Ukiyo E",
        "Mk Van Gogh",
        "Mk Vintage Airline Poster",
        "Mk Vintage Travel Poster",
        "Mk Vitreous Enamel",
        "Neo Baroque",
        "Neo Byzantine",
        "Neo Futurism",
        "Neo Impressionism",
        "Neo Rococo",
        "Neoclassicism",
        "Op Art",
        "Ornate And Intricate",
        "Papercraft Collage",
        "Papercraft Flat Papercut",
        "Papercraft Kirigami",
        "Papercraft Paper Mache",
        "Papercraft Paper Quilling",
        "Papercraft Papercut Collage",
        "Papercraft Papercut Shadow Box",
        "Papercraft Stacked Papercut",
        "Papercraft Thick Layered Papercut",
        "Pebble Art",
        "Pencil Sketch Drawing",
        "Photo Alien",
        "Photo Film Noir",
        "Photo Glamour",
        "Photo Hdr",
        "Photo Iphone Photographic",
        "Photo Long Exposure",
        "Photo Neon Noir",
        "Photo Silhouette",
        "Photo Tilt Shift",
        "Pop Art 2",
        "Random Style",
        "Rococo",
        "SAI 3D Model",
        "SAI Analog Film",
        "SAI Anime",
        "SAI Cinematic",
        "SAI Comic Book",
        "SAI Craft Clay",
        "SAI Digital Art",
        "SAI Enhance",
        "SAI Fantasy Art",
        "SAI Isometric",
        "SAI Line Art",
        "SAI Lowpoly",
        "SAI Neonpunk",
        "SAI Origami",
        "SAI Photographic",
        "SAI Pixel Art",
        "SAI Texture",
        "Silhouette Art",
        "Simple Vector Art",
        "Sketchup",
        "Steampunk 2",
        "Sticker Designs",
        "Suprematism",
        "Surrealism",
        "Terragen",
        "Tranquil Relaxing Atmosphere",
        "Vibrant Rim Light",
        "Volumetric Lighting",
        "Watercolor 2",
        "Whimsical And Playful"
    ]
]
